-- LEGADO: use a pasta supabase/migrations/
--
-- Projeto novo  → rode migrations/20260923100000_init.sql
-- Já tinha banco → rode migrations/20260923100100_mark_existing_as_migrated.sql
-- Mudança nova  → yarn db:migration:new descricao  e rode só o arquivo novo
--
-- Guia: supabase/migrations/README.md
